Description: default-vpc-deleter
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      RoleName: default-vpc-deleter-role
      Policies:
        - PolicyName: default-vpc-deleter-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                  - iam:PassRole
                Resource:
                  - arn:aws:iam::*:role/default-vpc-deleter-target-account-role
              - Effect: Allow
                Action:
                  - ec2:DescribeVpcs
                  - ec2:DescribeInternetGateways
                  - ec2:DetachInternetGateway
                  - ec2:DescribeSubnets
                  - ec2:DeleteSubnet
                  - ec2:DeleteVpc
                Resource:
                  - "*"
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      TimeoutInMinutes: 5
      Description: delete's the default vpc in a specified account
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: ARM_CONTAINER
      Name: default-vpc-deleter
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: GITHUB
        Auth:
          Type: OAUTH
        Location: https://github.com/AlexChesters/default-vpc-deleter.git
        BuildSpec: buildspec.yml
      SourceVersion: all-in-step-fn
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: state-machine-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Effect: Allow
                  Action:
                    - codebuild:StartBuild
                    - codebuild:StopBuild
                    - codebuild:BatchGetBuilds
                  Resource: !GetAtt CodeBuildProject.Arn
                - Effect: Allow
                  Action:
                    - ec2:DescribeRegions
                  Resource:
                    - "*"
                - Effect: Allow
                  Action:
                    - events:PutTargets
                    - events:PutRule
                    - events:DescribeRule
                  Resource:
                  - !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventForCodeBuildStartBuildRule"
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: default-vpc-deleter
      RoleArn: !GetAtt StateMachineRole.Arn
      Definition:
        StartAt: DescribeRegions
        States:
          DescribeRegions:
            Type: Task
            Parameters: {}
            Resource: arn:aws:states:::aws-sdk:ec2:describeRegions
            OutputPath: "$.Regions"
            Next: DeleteVPC
          DeleteVPC:
            Type: Map
            InputPath: "$"
            ItemsPath: "$"
            MaxConcurrency: 1
            Iterator:
              StartAt: "CodeBuild"
              States:
                CodeBuild:
                  Type: Task
                  Resource: arn:aws:states:::codebuild:startBuild.sync
                  Parameters:
                    ProjectName: !Ref CodeBuildProject
                    EnvironmentVariablesOverride:
                      - Name: REGION
                        'Value.$': "$.RegionName"
                        Type: "PLAINTEXT"
                      - Name: ACCOUNT_ID
                        'Value.$': "$$.Execution.Input.account_id"
                        Type: "PLAINTEXT"
                  End: true
            End: true
  StateMachineFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !ImportValue notification-topic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref StateMachine
      EvaluationPeriods: 1
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Period: 86400 # one day
      TreatMissingData: notBreaching
      Statistic: Sum
      Threshold: 1
