Description: default-vpc-deleter
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      RoleName: default-vpc-deleter-role
      Policies:
        - PolicyName: default-vpc-deleter-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                  - iam:PassRole
                Resource:
                  - arn:aws:iam::*:role/default-vpc-deleter-target-account-role
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      TimeoutInMinutes: 5
      Description: delete's the default vpc in a specified account
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        Type: ARM_CONTAINER
      Name: default-vpc-deleter
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: GITHUB
        Auth:
          Type: OAUTH
        Location: https://github.com/AlexChesters/default-vpc-deleter.git
        BuildSpec: buildspec.yml
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: state-machine-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Effect: Allow
                  Action:
                    - codebuild:StartBuild
                    - codebuild:StopBuild
                    - codebuild:BatchGetBuilds
                  Resource: !GetAtt CodeBuildProject.Arn
                - Effect: Allow
                  Action:
                    - events:PutTargets
                    - events:PutRule
                    - events:DescribeRule
                  Resource:
                  - !Sub "arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventForCodeBuildStartBuildRule"
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: default-vpc-deleter
      RoleArn: !GetAtt StateMachineRole.Arn
      Definition:
        StartAt: CodeBuild
        States:
          CodeBuild:
            Type: Task
            Resource: arn:aws:states:::codebuild:startBuild.sync
            ResultPath: $
            OutputPath: $
            End: true
            Parameters:
              ProjectName: !Ref CodeBuildProject
              EnvironmentVariablesOverride:
                - Name: "ACCOUNT_ID"
                  'Value.$': "$$.Execution.Input.account_id"
                  Type: "PLAINTEXT"
